#! /bin/sh

test x"$SHELL" = x"" && SHELL=/bin/bash
test x"$1"     = x"" && set -- default

if test -r /etc/default/keyboard &&
   test -x /usr/bin/setxkbmap; then
  . /etc/default/keyboard
  /usr/bin/setxkbmap \
    -model   "${XKBMODEL}" \
    -layout  "${XKBLAYOUT}" \
    -variant "${XKBVARIANT}" \
    "${XKBOPTIONS}"
fi

#unset SESSION_MANAGER # 若 vnc 和登录所用 session 不一样, 就需要这个

export GTK_IM_MODULE=ibus
export GTK_MODULES=gail:atk-bridge
export CLUTTER_IM_MODULE=ibus
export QT_IM_MODULE=ibus
export QT_ACCESSIBILITY=1
export QT_AUTO_SCREEN_SCALE_FACTOR=0
export QT_QPA_PLATFORMTHEME=qt5ct
export XMODIFIERS=@im=ibus
export XDG_DATA_DIRS=/usr/share/xfce4:/usr/local/share/:/usr/share/:/usr/share

/usr/bin/ibus-daemon -d -x -r &

tigervncconfig -iconic &
"$SHELL" -l <<EOF
exec /etc/X11/Xsession "$@"
EOF

#vncconfig -iconic &
#dbus-launch --exit-with-session startxfce4
